### ISSUE TITLE
post image issues when attempting to self-host script

### ISSUE THREAD

**Issue by caljess599** [chrisj74/vue-rss-blog#14] opened 2020-12-05 16:37 UTC
I went ahead and tried to build my own so I could remove/change the h2 tag in the post-title, but either I'm not understanding what I need to do or weebly is just causing havock.

Here is what the slider vue looks like (with some custom css) using the twilink-hosted script:
![image](https://user-images.githubusercontent.com/9257280/101256979-9501bc00-36ed-11eb-82f9-79b0c44cdda6.png)

But here is that exact same code (with the same custom css) that I've built and uploaded:
![image](https://user-images.githubusercontent.com/9257280/101257466-bbbff280-36ed-11eb-9dd4-60e9ed6b7e30.png)

Any help you could provide would be appreciated. Thx

**Comment by chrisj74** [comment] 2020-12-05 17:35
Hi

I assume weebly allows you to add custom css? If so you should be able to use the Twilik hosted script and just update the css this way, no need to build and upload etc. 

I’m afraid without a link to see the page I can’t really help with how to stop weebly interfering. Alternatively if you include the css you are using I may be able to offer some suggestions.

**Comment by chrisj74** [comment] 2020-12-08 19:51
closing as a duplicate of #13

**Closed by chrisj74** 2020-12-08 19:51 UTC
